export interface Gift {
  id: number;
  name: string;
  description: string;
  price: string;
  image: string;
  featured?: boolean;
}

export const gifts: Gift[] = [
  {
    id: 1,
    name: "Cash Gift",
    description: "Monetary contribution to support our new journey together",
    price: "Any amount",
    image: "/money2.jpg",
    featured: true,
  },
  {
    id: 2,
    name: "Air Conditioner",
    description: "High-efficiency air conditioner for a cool home",
    price: "₦300,000",
    image: "/ac.jpg",
  },
  {
    id: 3,
    name: "Bedding Set",
    description: "Premium cotton bedding set for comfortable nights",
    price: "₦25,000",
    image: "/bedsheet.jpg",
  },
  {
    id: 4,
    name: "Blender",
    description: "High-speed blending machine for smoothies and more",
    price: "₦75,000",
    image: "/blender.jpg",
  },
  {
    id: 5,
    name: "Bookshelf",
    description: "Stylish bookshelf for a growing library",
    price: "₦45,000",
    image: "/bookshelf.jpg",
  },
  {
    id: 6,
    name: "Chair",
    description: "Comfortable accent chair for your living space",
    price: "₦50,000",
    image: "/chair.jpg",
  },
  {
    id: 7,
    name: "Cup Set",
    description: "Elegant cup set for tea and coffee",
    price: "₦15,000",
    image: "/cup.jpg",
  },
  {
    id: 8,
    name: "Refrigerator",
    description: "Double-door refrigerator for fresh food storage",
    price: "₦280,000",
    image: "/fridge.jpg",
  },
  {
    id: 9,
    name: "Air Fryer",
    description: "Healthy cooking with less oil",
    price: "₦85,000",
    image: "/fryer.jpg",
  },
  {
    id: 10,
    name: "Frying Pan Set",
    description: "Non-stick frying pan set for everyday cooking",
    price: "₦30,000",
    image: "/frypan.jpg",
  },
  {
    id: 11,
    name: "Steam Iron",
    description: "Powerful steam iron for wrinkle-free clothes",
    price: "₦25,000",
    image: "/iron.jpg",
  },
  {
    id: 12,
    name: "Ironing Board",
    description: "Sturdy ironing board with adjustable height",
    price: "₦20,000",
    image: "/ironboard.jpg",
  },
  {
    id: 13,
    name: "Electric Kettle",
    description: "Fast-boiling electric kettle",
    price: "₦18,000",
    image: "/kettle.jpg",
  },
  {
    id: 14,
    name: "Knife Set",
    description: "Professional kitchen knife set",
    price: "₦35,000",
    image: "/knife.jpg",
  },
  {
    id: 15,
    name: "Laundry Bag",
    description: "Durable laundry bag for organization",
    price: "₦8,000",
    image: "/laundarybag.jpg",
  },
  {
    id: 16,
    name: "Microwave Oven",
    description: "Modern microwave oven for quick meals",
    price: "₦65,000",
    image: "/microwave.jpg",
  },
  {
    id: 17,
    name: "Plate Rack",
    description: "Stainless steel plate rack for kitchen organization",
    price: "₦25,000",
    image: "/platerack.jpg",
  },
  {
    id: 18,
    name: "Dinner Plates",
    description: "Elegant dinner plate set",
    price: "₦20,000",
    image: "/plates.jpg",
  },
  {
    id: 19,
    name: "Cooking Pots",
    description: "Quality cooking pot set",
    price: "₦45,000",
    image: "/pots.jpg",
  },
  {
    id: 20,
    name: "Area Rug",
    description: "Beautiful area rug for your living room",
    price: "₦40,000",
    image: "/rug.jpg",
  },
  {
    id: 21,
    name: "Throw Pillows",
    description: "Decorative throw pillows for your sofa",
    price: "₦12,000",
    image: "/throwp.jpg",
  },
  {
    id: 22,
    name: "Toaster",
    description: "2-slice toaster for perfect breakfast",
    price: "₦22,000",
    image: "/toaster.jpg",
  },
  {
    id: 23,
    name: "Television",
    description: "Smart TV for family entertainment",
    price: "₦350,000",
    image: "/tv.jpg",
  },
  {
    id: 24,
    name: "Washing Machine",
    description: "Automatic washing machine for laundry convenience",
    price: "₦250,000",
    image: "/washingm.jpg",
  },
];
