export interface Gift {
  id: number;
  name: string;
  price: string;
  image: string;
  description: string;
  featured?: boolean;
}

export const gifts: Gift[] = [
  {
    id: 0,
    name: "Cash Gift",
    price: "Any Amount",
    image: "/money2.jpg",
    description: "Support our new journey with a cash contribution.",
    featured: true,
  },
  {
    id: 1,
    name: "Baby Bottles",
    price: "₦25,000",
    image: "/baby-bottles.jpeg",
    description: "Anti-colic feeding bottles for a happy baby.",
    featured: true,
  },
  {
    id: 2,
    name: "Breast Pump",
    price: "₦45,000",
    image: "/breast-pump.jpeg",
    description: "Electric breast pump for efficient nursing.",
  },
  {
    id: 3,
    name: "Nursing Bra",
    price: "₦12,000",
    image: "/nursing-bra.jpeg",
    description: "Comfortable and supportive nursing bras.",
  },
  {
    id: 4,
    name: "Burp Cloth",
    price: "₦8,500",
    image: "/burp-cloth.jpeg",
    description: "Soft and absorbent cotton burp cloths.",
  },
  {
    id: 5,
    name: "Bottle Brush & Sterilizer",
    price: "₦35,000",
    image: "/bottle-sterilizer.jpeg",
    description: "Keeping bottles clean and germ-free.",
  },
  {
    id: 6,
    name: "Onesies and Baby Suits",
    price: "₦15,000",
    image: "/onesies.jpeg",
    description: "Set of soft cotton onesies for daily wear.",
  },
  {
    id: 7,
    name: "Sleepsuits",
    price: "₦18,000",
    image: "/sleepsuits.jpeg",
    description: "Cozy sleepsuits for a peaceful night's rest.",
  },
  {
    id: 8,
    name: "Socks, Booties & Mittens",
    price: "₦5,500",
    image: "/socks-booties.jpeg",
    description: "Keeping tiny hands and feet warm.",
  },
  {
    id: 9,
    name: "Blankets & Swaddles",
    price: "₦22,000",
    image: "/blankets-swaddles.jpeg",
    description: "Breathable swaddles and warm blankets.",
  },
  {
    id: 10,
    name: "Fitted Bed Sheet",
    price: "₦10,000",
    image: "/fitted-sheet.jpeg",
    description: "Soft fitted sheets for the baby's cot.",
  },
  {
    id: 11,
    name: "Diapers",
    price: "₦15,000",
    image: "/diapers.jpeg",
    description: "A pack of high-quality newborn diapers.",
  },
  {
    id: 12,
    name: "Baby Wipes",
    price: "₦8,000",
    image: "/baby-wipes.jpeg",
    description: "Gentle and fragrance-free baby wipes.",
  },
  {
    id: 13,
    name: "Cotton Wool",
    price: "₦4,500",
    image: "/cotton-wool.jpeg",
    description: "Pure cotton wool for delicate cleaning.",
  },
  {
    id: 14,
    name: "Changing Mat",
    price: "₦12,500",
    image: "/changing-mat.jpeg",
    description: "Portable and waterproof changing mat.",
  },
  {
    id: 15,
    name: "Diaper Rash Cream",
    price: "₦6,000",
    image: "/diaper-rash-cream.jpeg",
    description: "Protective cream for smooth baby skin.",
  },
  {
    id: 16,
    name: "Diaper Bag",
    price: "₦28,000",
    image: "/diaper-bag.jpeg",
    description: "Stylish and spacious diaper bag.",
  },
  {
    id: 17,
    name: "Baby Bath Set",
    price: "₦18,500",
    image: "/baby-bath-set.jpeg",
    description: "Complete bath set including tub and accessories.",
  },
  {
    id: 18,
    name: "Soft Towel & Wash Cloth",
    price: "₦9,000",
    image: "/soft-towel.jpeg",
    description: "Gentle towels for post-bath snuggles.",
  },
  {
    id: 19,
    name: "Nail Clipper",
    price: "₦3,500",
    image: "/nail-clipper.jpeg",
    description: "Safety nail clippers for baby's grooming.",
  },
  {
    id: 20,
    name: "Thermometer",
    price: "₦7,500",
    image: "/thermometer.jpeg",
    description: "Digital thermometer for accurate temperature checks.",
  },
  {
    id: 21,
    name: "Nasal Aspirator",
    price: "₦5,000",
    image: "/nasal-aspirator.jpeg",
    description: "Easy-to-use nasal aspirator for clear breathing.",
  },
  {
    id: 22,
    name: "Car Seat",
    price: "₦120,000",
    image: "/car-seat.jpeg",
    description: "Safety-certified car seat for travel protection.",
    featured: true,
  },
  {
    id: 23,
    name: "Baby Swing",
    price: "₦85,000",
    image: "/baby-swing.jpeg",
    description: "Soothing baby swing with multiple speeds.",
  },
  {
    id: 24,
    name: "White Noise Machine",
    price: "₦15,000",
    image: "/white-noise-machine.jpeg",
    description: "Helping baby sleep with soothing sounds.",
  },
  {
    id: 25,
    name: "Play Mat",
    price: "₦25,000",
    image: "/play-mat.jpeg",
    description: "Interactive play mat for tummy time.",
  },
  {
    id: 26,
    name: "Baby Monitor",
    price: "₦55,000",
    image: "/baby-monitor.jpeg",
    description: "Video monitor to keep an eye on your little one.",
  },
  {
    id: 27,
    name: "High Feeding Chair",
    price: "₦45,000",
    image: "/high-chair.jpeg",
    description: "Ergonomic high chair for meal times.",
  },
  {
    id: 28,
    name: "Baby Bottle Warmer",
    price: "₦20,000",
    image: "/bottle-warmer.jpeg",
    description: "Quick and even warming for baby's milk.",
  },
  {
    id: 29,
    name: "Baby Storage Drawer",
    price: "₦75,000",
    image: "/storage-drawer.jpeg",
    description: "Spacious storage for all baby essentials.",
    featured: true,
  },
];
